name: entrance_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_gen: ^5.3.2
  get: 4.6.6
  get_storage: ^2.1.1
  dio: ^5.3.3
  flutter_svg: ^2.0.7
  flutter_sizer: ^1.0.5
  keyboard_dismisser: ^3.0.0
  json_annotation: ^4.8.1
  awesome_dio_interceptor: ^1.0.0
  retrofit: '>=4.0.0 <5.0.0'
  logger: any
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: any
  flutter_gen_runner: any
  json_serializable: ^6.7.1
  retrofit_generator: '>=5.0.0 <6.0.0'
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

